# Blueprint versi 3 - Final & Corrected
databases:
  # Definisi database (ini sudah benar)
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: free
    postgresMajorVersion: 15

services:
  # Definisi web service Laravel
  - type: web
    name: portfolio-web
    runtime: php # <-- DIUBAH: dari 'env' menjadi 'runtime'
    plan: free
    
    buildCommand: |
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
      php artisan migrate --force

    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

    # Environment Variables
    envVars:
      # DIHAPUS: Blok untuk APP_URL kita hapus dari sini, akan di-set manual
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: portfolio-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portfolio-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: portfolio-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: portfolio-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password