databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: free
    postgresMajorVersion: 15

services:
  - type: web
    name: portfolio-web
    env: docker # <-- INI PERUBAHAN UTAMA. Kita beritahu Render untuk menggunakan Docker
    plan: free
    healthCheckPath: / # Path untuk memeriksa apakah aplikasi sehat
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: portfolio-web
          property: url
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - fromDatabase:
          name: portfolio-db
          property: connectionString
        key: DATABASE_URL