# Blueprint versi 4 - Final, Corrected for Docker
databases:
  # Definisi database
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio_user
    plan: free
    postgresMajorVersion: 15

services:
  # Definisi web service Laravel menggunakan Docker
  - type: web
    name: portfolio-web
    env: docker # <-- Memberitahu Render untuk menggunakan Dockerfile Anda
    plan: free
    healthCheckPath: /
    
    # Environment Variables
    envVars:
      # APP_URL DIHAPUS DARI SINI. AKAN DISET SECARA MANUAL DI DASHBOARD RENDER.
      - key: APP_KEY
        generateValue: true # Biarkan Render membuat APP_KEY baru yang aman
      - key: DB_CONNECTION
        value: pgsql
      # Mengambil connection string lengkap dari service database
      - fromDatabase:
          name: portfolio-db
          property: connectionString
        key: DATABASE_URL