# Blueprint versi 2 - Struktur yang Benar untuk Laravel + Database
databases:
  # Mendefinisikan service database kita terlebih dahulu
  - name: portfolio-db       # Nama database Anda
    databaseName: portfolio  # Nama database spesifik yang akan dibuat
    user: portfolio_user     # Username untuk database
    plan: free               # Menggunakan paket gratis
    postgresMajorVersion: 15 # Menggunakan PostgreSQL versi 15

services:
  # Mendefinisikan web service untuk aplikasi Laravel
  - type: web
    name: portfolio-web      # Nama web service Anda
    env: php                 # Environment PHP
    plan: free               # Paket gratis
    
    # Perintah yang dijalankan saat build
    buildCommand: |
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      npm install
      npm run build
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link
      php artisan migrate --force

    # Perintah untuk menjalankan aplikasi
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

    # Environment Variables
    envVars:
      - key: APP_URL
        # Render akan memberikan URL-nya secara otomatis
        fromService:
          type: web
          name: portfolio-web
          property: url
      - key: APP_KEY
        generateValue: true # Biarkan Render membuat APP_KEY baru yang aman
      - key: DB_CONNECTION
        value: pgsql # Driver PostgreSQL untuk Laravel
      # Mengambil detail koneksi dari service database yang kita definisikan di atas
      - key: DB_HOST
        fromDatabase:
          name: portfolio-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: portfolio-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: portfolio-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: portfolio-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: portfolio-db
          property: password